### ISSUE TITLE
cannot expand single item

### ISSUE THREAD

**Issue by jeffwllms** [dtolnay/cargo-expand#50] opened 2019-03-10 18:32 UTC
I have an issue expanding a single item.  I get the error "cannot expand single item (single::item) without rustfmt"  it does give the hint to install rustfmt using "rustup component add rustfmt --toolchain nightly"

however when i run that it says rustfmt is up to date.  Even installing to stable is up to date.  to the best I can tell rustfmt is installed fine for all toolchains.  

not sure if there is a bug or I am simply doing something wrong.

**Comment by dtolnay** [comment] 2019-03-11 01:05
Uh-oh, it sounds like you are doing everything right and it should be working.

What operating system / target are you using? It would be helpful to see the output of:

```console
$ rustc -vV
$ cargo -vV
```

Is there a rustc or cargo on your system installed some other way than by rustup, such as by the OS's package manager?

Is `$RUSTUP_HOME` defined in your shell? (It probably won't be, but it is relevant to how we locate rustfmt.)

```console
$ echo $RUSTUP_HOME
```

Does your toolchain live somewhere other than `~/.rustup/toolchains`?

```console
$ ls ~/.rustup/toolchains/*/bin/rustfmt
```

Is there a rustfmt on the PATH and separately, is there a rustfmt that rustup prefers to find?

```console
$ which rustfmt
$ rustfmt --version
$ rustup which rustfmt
$ rustup run nightly rustfmt --version
```

@gsquire, any other details that would help figure this out?

**Comment by ehuss** [comment] 2019-03-11 03:16
I'm seeing the same behavior.  It looks like `toolchain_find` has a few issues.
- Doesn't work on Windows.  It doesn't check for `.exe` extensions.
- On other platforms, it doesn't work if there is a rustc with an unusual version number. For example, I use `rustup link` to link stage1 or stage2 when building rustc locally.  `toolchain_find` iterates through all toolchains running `rustc -V`, and when it fails to parse the version format (`rustc 1.35.0-dev`), it aborts and stops checking any additional toolchains (due to the `?` [here](https://github.com/gsquire/toolchain_find/blob/61871c98312e91e0a6e80fef652fd8d992620a44/src/lib.rs#L115)).

I'm guessing toolchain_find is used so it can use any available rustfmt?  Seems to me like it would be sufficient to just run `rustfmt` and assume it is installed for nightly.

**Comment by dtolnay** [comment] 2019-03-11 03:32
Thanks @ehuss, I filed https://github.com/gsquire/toolchain_find/issues/6 and https://github.com/gsquire/toolchain_find/issues/7 for your two observations.

<br>

> Seems to me like it would be sufficient to just run rustfmt and assume it is installed for nightly.

I would prefer to fix toolchain_find instead. Nightly rustfmt is flaky. I often need to remove rustfmt from the nightly toolchain in order to update nightly because rustfmt is missing from that nightly. I would like to still see formatted code when that happens.

**Comment by gsquire** [comment] 2019-03-11 15:08
I think you asked the right questions and I will follow this thread to see if the user reports any other interesting information.

As far as the other two issues go, I'll start digging into them. I definitely overlooked Windows having the file extension when searching for a binary. I think the other issue should be fixed with 0.1.3 but I will double check and update the issues in the repository.

**Comment by gsquire** [comment] 2019-03-12 17:39
I published version 0.1.4 of toolchain_find. I added an integration test to ensure it works on Windows.

If you want to give it a spin, please reinstall cargo-expand with:

```sh
cargo install --force cargo-expand
```

Feel free to drop on issue in my [repository](https://github.com/gsquire/toolchain_find) if you still run into problems. Thanks!

**Comment by dtolnay** [comment] 2019-03-12 19:27
I published cargo-expand 0.4.10 which pulls in toolchain_find 0.1.4. @jeffwllms could you let me know whether it works after updating?

**Comment by jeffwllms** [comment] 2019-03-12 21:07
@gsquire @dtolnay just did the reinstall and all looks like I am not getting that error any longer.  However it seems to hang and doesn't actually output.  Even if i don't do a single item (cargo expand) which used to work.

But I may be just doing something else incorrectly.  But either way, I no longer get the error I was getting.

**Comment by dtolnay** [comment] 2019-03-12 21:45
Uh-oh, that sounds bad. I yanked 0.4.10 for now until we get a chance to look into that.

@gsquire can you think of anything in toolchain_find that might hang? If not, that means it would be something in cargo-expand after the place that we call toolchain_find, or something called by cargo-expand like rustfmt itself or the prettyprint crate.

@jeffwllms are you up for doing some debugging to narrow down what might be hanging? I would approach this by checking out cargo-expand and inserting printlns in src/main.rs to identify the last line that gets run. After making a change you can run the following to have cargo-expand expand its own source code:

```bash
cargo run -- expand
```

If you understandably don't want to spend more time on this issue, I'll try to put out a new release with some extra-verbose logging behind a flag and maybe we can use that to track down the problem. Thanks for your help and sorry that everything hasn't been working.

The details in https://github.com/dtolnay/cargo-expand/issues/50#issuecomment-471373418 would still be helpful.

**Comment by jeffwllms** [comment] 2019-03-12 21:50
@dtolnay sure, i will see if i get some time tonight to check out cargo-expand and see if I can do and debugging that will help.

**Comment by gsquire** [comment] 2019-03-12 22:23
>  can you think of anything in toolchain_find that might hang?

I would be surprised but here is what I can gather from a quick glance:
- Walking the toolchain directory and encountering circular symlinks
- Running `Command::new` to get the `rustc` version

These seem unlikely but other than that I can't imagine something else blocking execution. If @jeffwllms would be able to share the information you asked for originally, that would be great too. Then I can use `strace` and attempt to debug in other ways too.

**Comment by jeffwllms** [comment] 2019-03-13 12:26
@gsquire @dtolnay Sorry, i must have missed the post with the questions.  Below are some answers:

Operating System: Windows 10
Toolchain: x86_64-pc-windows-msvc (stable and nightly installed)
Rustc: 1.33.0 (stable); 1.35.0 (Nightly)
Cargo: 1.33.0
Only installed version is via rustup
RUSTUP_HOME: Not defined in shell
Toolchain are inside .rustup/toolchains
Doesn't look like there is a rustfmt found standalone or differrenet than installed via rustup.  But there are 2 versions in the stable toolschain 1.0.1  and the nightly toolchain 1.0.3


Hope this helps some

**Comment by gsquire** [comment] 2019-03-13 19:15
Based on the fact that you aren't seeing the `rustfmt` missing message anymore, I'm willing to say that my patch fixed Windows installs (unless someone proves me wrong).

If you are able to share the source that you are trying to expand, that would be helpful too. That way I can see if it also hangs on my machine or if there is something else going on.

**Comment by jeffwllms** [comment] 2019-03-14 13:24
so I test just the basic hello world you get when you do cargo new.  Cargo expand did fine.  The crate that isnt currently working is hyperium/http  which is a good size crate.  Howerver, i will say that prior i was able to "cargo expand" and have it expand everything.  The only thing that didn't work was the expanding of a single item.  Now neither works.

What i have tried.  cargo expand --ugly; works just fine for the entire crate.  It says can't use ugly for single mode.

Without the --ugly it hangs trying to expand the entire crate or just a single item.  The last output I get before it hangs is "Finished dev [unoptimized + debuginfo] target(s) in 1.39s"

If you would like me to share anything else please let me know.

**Comment by gsquire** [comment] 2019-03-14 16:46
Thanks for sharing your use case. I was able to reproduce this and see that `rustfmt` hangs when trying to run against the temporary file. FYI @dtolnay I didn't have a nightly `rustfmt` and when you add the `normalize_doc_attributes = true\n` attribute, it wouldn't acknowledge it on the stable toolchain since it's nightly only. Adding `rustfmt` for the nightly toolchain got rid of this message. However, it still hangs regardless.

What I did next is print the location of `rustfmt` and the temporary file and tried to run the same command in a terminal and saw the same behavior. I verified that `rustfmt` is valid by printing the version and help messages. I am still investigating why `rustfmt` isn't running but I figured I would share what I have so far.

**Comment by dtolnay** [comment] 2019-03-14 19:15
@gsquire could you file a separate issue with the normalize_doc_attributes message you are seeing? I was not able to reproduce this even with only a stable rustfmt installed. It left doc comments as attributes but otherwise no warning was printed.

I unyanked cargo-expand 0.4.10 since it seems that the hang originates from rustfmt and not from cargo-expand.

I think the hang is associated with [this `eq!` macro](https://github.com/hyperium/http/blob/7cd66aa82aa2499992c4b76c89d851b53f6abb7d/src/header/name.rs#L1500) in the http crate. For example that one line expands to something like:

```rust
fn eq() -> bool {
    (b[0] == b'c' &&
    (b[1] == b'o' &&
    (b[(1 + 1)] == b'n' &&
    (b[((1 + 1) + 1)] == b't' &&
    (b[(((1 + 1) + 1) + 1)] == b'e' &&
    (b[((((1 + 1) + 1) + 1) + 1)] == b'n' &&
    (b[(((((1 + 1) + 1) + 1) + 1) + 1)] == b't' &&
    (b[((((((1 + 1) + 1) + 1) + 1) + 1) + 1)] == b'-' &&
    (b[(((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b's' &&
    (b[((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'e' &&
    (b[(((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'c' &&
    (b[((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'u' &&
    (b[(((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'r' &&
    (b[((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'i' &&
    (b[(((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b't' &&
    (b[((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'y' &&
    (b[(((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'-' &&
    (b[((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'p' &&
    (b[(((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'o' &&
    (b[((((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'l' &&
    (b[(((((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'i' &&
    (b[((((((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'c' &&
    (b[(((((((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'y' &&
    (b[((((((((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'-' &&
    (b[(((((((((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'r' &&
    (b[((((((((((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'e' &&
    (b[(((((((((((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'p' &&
    (b[((((((((((((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'o' &&
    (b[(((((((((((((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'r' &&
    (b[((((((((((((((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b't' &&
    (b[(((((((((((((((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'-' &&
    (b[((((((((((((((((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'o' &&
    (b[(((((((((((((((((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'n' &&
    (b[((((((((((((((((((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'l' &&
    (b[(((((((((((((((((((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)] == b'y'
    )))))))))))))))))))))))))))))))))))
}
```

which is understandably complicated to format. I will minimize further and file a rustfmt issue.

**Comment by gsquire** [comment] 2019-03-14 19:28
Sorry, I realized I see that error when running `rustfmt` directly and not inside of `cargo expand`. You already ignore the errors that occur so it really isn't an issue after all.

Good find on that macro, definitely seems like the issue is outside of `cargo expand`.

**Comment by gsquire** [comment] 2019-03-15 23:45
@jeffwllms Thanks to the patch @dtolnay added to the http crate, you can now run `cargo expand` without issue. If you pull the latest master branch, you shouldn't see any more hangs like you did previously.

Hope all your issues are resolved at this point now :)

**Comment by jeffwllms** [comment] 2019-03-18 14:23
@gsquire and @dtolnay  sorry for my late response, I have been sick so I was out of it for a while.  I pulled the newest http crate down and can confirm that it does now in fact work.  I will say one thing when I originally posted "cargo expand" did work it was only trying to do path::to::item that gave the original error.  Which kind of to me says rustfmt maybe was able to expand the eq! macro at one point.  

But know I also wonder in writing my own macros, is there somewhere to possible read about how to write macro in a way so you can avoid this having this issue, writing macro so it is compatible with rustfmt.

Anyway, that you guys so much for your help, you went above and beyond to the point of sending edits to someone else's crate.  this is one of the reason i have been loving learning rust so far, everyone is incredibly willing to help.

**Comment by gsquire** [comment] 2019-03-18 15:53
@jeffwllms Glad it works now!

As far as the issues with macro expansion inside of `rustfmt`, it really shouldn't cause an issue. Unless there is an overly recursive expansion, it should be able to properly format the source. I think an issue will be filed once there is a minimal example that can be replicated.

Hope you keep enjoying Rust!

**Comment by dtolnay** [comment] 2019-03-21 22:15
I filed https://github.com/rust-lang/rustfmt/issues/3465 to address the hang in rustfmt.

**Closed by dtolnay** 2019-03-21 22:15 UTC
